version: '3'

services:
  web:
    container_name: rails-web
    build:
      context: .
      dockerfile: ./infra/docker/ruby/Dockerfile
    command: bundle exec bin/rails server -p 3000 -b 0.0.0.0
    # command: /bin/sh -c "while :; do sleep 10; done"
    environment:
      MYSQL_USER: sql
      MYSQL_PASSWORD: password
    working_dir: /rails
    volumes:
      - ./rails:/rails
    ports:
      - '3000:3000'
  rails-db:
    container_name: rails-db
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3307}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./infra/docker/mysql/dump
        target: /dump
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-rails_dev}
      - MYSQL_USER=${DB_USERNAME:-sql}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}

volumes:
  db-store: